language: python
dist: trusty
services:
- docker
matrix:
  include:
  - stage: Nightly
  - stage: Large
  - language: r
    name: R
    cache: packages
    before_install:
    - rm -rf /home/travis/R/Library/mlflow
    - export NOT_CRAN=true
    - cd mlflow/R/mlflow
    - Rscript -e 'install.packages("devtools")'
    - Rscript -e 'devtools::install_deps(dependencies = TRUE, upgrade = FALSE)'
    - cd ../../..
    install:
    - source ./travis/install-common-deps.sh
    script:
    - cd mlflow/R/mlflow
    - R CMD build .
    - export LINTR_COMMENT_BOT=false
    - cd tests
    - Rscript ../.travis.R
    after_success:
    - export COVR_RUNNING=true
    - Rscript -e 'covr::codecov()'
    after_failure:
    - '[ -r /home/travis/build/mlflow/mlflow/mlflow/R/mlflow/mlflow.Rcheck/00check.log
      ] && cat /home/travis/build/mlflow/mlflow/mlflow/R/mlflow/mlflow.Rcheck/00check.log'
  - os: windows
    name: Windows
    language: sh
    before_install:
    - choco install python3 --version=3.7.4
    install:
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    - pip install -r dev-requirements.txt
    - pip install -r travis/small-requirements.txt
    - pip install -e .
    script:
    - pytest --verbose --ignore-flavors --ignore=tests/projects tests
install:
- echo "Build stage $TRAVIS_BUILD_STAGE_NAME";
- CHANGED_FILES=$(git diff --name-only master..HEAD | grep "tests/examples\|examples")
  || true;
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then echo "skipping this step on windows.";
  elif [[ "$TRAVIS_BUILD_STAGE_NAME" == "Nightly" ]] && ! [[ "$TRAVIS_EVENT_TYPE"
  == "cron" || ! -z "$CHANGED_FILES" ]]; then echo "skipping the nightly stage because
  this build is not nightly and there are no changed files associated with nightly
  tests."; else INSTALL_LARGE_PYTHON_DEPS=true source ./travis/install-common-deps.sh;
  fi;
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
